all: main

main: main.cpp src/WebManager.cpp src/PageRenderer.cpp src/HTMLParser.cpp src/UserInterface.cpp
	g++ -o main main.cpp src/WebManager.cpp src/PageRenderer.cpp src/HTMLParser.cpp src/UserInterface.cpp -lncurses
